Set coast on disable
AndromedaOne/2020Code pull request #137
Opened 2021-03-04 23:53 UTC by MasonPyatt

Robot goes on coast mode when disabled

2021-03-05 00:41 UTC, SPD3 requested changes
It looks like we only go back into break mode when the robot is initialized but really we want to go into break mode whenever the robot is enabled in Teleop, auto, test or practice mode(whenever the robot is ever enabled)

2021-03-06 19:01 UTC, MasonPyatt commented
@SPD3 The robot will now turn off coast mode whenever Teleop, Autonomous, or test modes are initialized

2021-03-08 23:43 UTC, SPD3 approved these changes

2021-05-24 23:00 UTC, schleprock commented
already merged to main via the new WPILIB update

2021-05-24 23:00 UTC, closed without merging