Led lights subsystem
AndromedaOne/2020Code pull request #138
Opened 2021-03-06 18:12 UTC by MasonPyatt

Created the LED light system, including when it blinks and changes colors. Also copied some shooter RPM values from TDYLF to Roadkill to prevent the code from crashing

2021-03-06 18:18 UTC, themccubbins commented
Can we spotless etc to make the build work?

2021-03-06 18:29 UTC, themccubbins requested changes

2021-03-06 18:29 UTC, themccubbins commented on src/main/deploy/robotConfigs/RoadKill/Shooter.conf
> +    backOfGreenZone = 4400
Seems unrelated to this PR?

2021-03-06 18:29 UTC, themccubbins commented on src/main/java/frc/robot/telemetries/TraceEntry.java
> +package frc.robot.telemetries;
This file is unrelated to this PR, delete before merging. 

This is happening because this is a new file on the trace branch and isn't deleted when we switch branches.

2021-03-06 19:42 UTC, MasonPyatt commented on src/main/deploy/robotConfigs/RoadKill/Shooter.conf
> +    backOfGreenZone = 4400
Necessary for testing on Roadkill

2021-03-07 00:05 UTC, themccubbins approved these changes
lgtm

2021-03-08 23:39 UTC, merged